version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network
    depends_on:
      - db
      - redis
      - mailhog
      - minio_setup

  webserver:
    image: nginx:alpine
    container_name: laravel_nginx
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    networks:
      - laravel_network
    depends_on:
      - app

  db:
    image: mysql:latest
    container_name: laravel_db
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=laravel_user
      - MYSQL_PASSWORD=laravel_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - laravel_network

  redis:
    image: redis:alpine
    container_name: laravel_redis
    ports:
      - 6379:6379
    networks:
      - laravel_network

  mailhog:
    image: mailhog/mailhog
    container_name: laravel_mailhog
    ports:
      - 8025:8025
    networks:
      - laravel_network

  minio:
    image: minio/minio
    container_name: laravel_minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadminpassword
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000  # MinIO API
      - 9001:9001  # MinIO Console
    networks:
      - laravel_network
    volumes:
      - minio_data:/data

  minio_setup:
    image: minio/mc
    container_name: laravel_minio_setup
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        until (/usr/bin/mc alias set minio http://minio:9000 minioadmin minioadminpassword) do sleep 5; done &&
        /usr/bin/mc mb minio/testing
      "
    networks:
      - laravel_network

volumes:
  mysql_data:
  minio_data:

networks:
  laravel_network:
