name: Deploy to AWS with Terraform

on:
  push:
    branches:
      - main  
  workflow_dispatch: 

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Plan Terraform
        id: terraform_plan
        run: cd terraform && terraform init && terraform plan -out=tfplan
    
      #- uses: trstringer/manual-approval@v1
      #  with:
      #    secret: ${{ secrets.TOKEN }}
      #    approvers: janamkhatiwada
      #    minimum-approvals: 1
      #    issue-title: "Deploying to prod"
      #    issue-body: "Review the terraform plan, then approve or deny the deployment to prod."
      #    exclude-workflow-initiator-as-approver: false
#
      #- name: Terraform apply
      #  run: |
      #    cd terraform && terraform apply
