name: Deploy to AWS with Terraform

on:
  push:
    branches:
      - main  
  workflow_dispatch: 

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Plan Terraform
        id: terraform_plan
        run: cd terraform && terraform init && terraform plan -out=tfplan

      - name: Send email notification for review
        if: always()
        uses: dawidd6/action-send-mail@v3 
        with:
          server_address: smtp.gmail.com  
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}  
          password: ${{ secrets.EMAIL_PASSWORD }}  
          subject: "Terraform Plan Ready for Review"
          to: user@example.com 
          from: "no-reply@example.com"
          content_type: text/plain
          body: |
            The Terraform plan is ready for review.
            Please review the plan output in GitHub Actions logs.
            Approve deployment at the following URL:
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    
  wait-for-approval:
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: always()
    steps:
      - name: Await manual approval
        uses: andymckay/approve-pull-request@v1
        with:
          message: "Review and approve to continue with deployment"

  terraform-apply:
    runs-on: ubuntu-latest
    needs: wait-for-approval

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        run: terraform apply tfplan
